apiVersion: v1
kind: Template
labels:
  template: grafana-nodatasource
message: See https://github.com/nmasse-itix/OpenShift-Docker-Images/tree/master/grafana for more details.
metadata:
  annotations:
    description: |-
      The default configmaps for a vanilla Grafana.
    openshift.io/display-name: Grafana
    tags: instant-app
    template.openshift.io/documentation-url: https://github.com/nmasse-itix/OpenShift-Docker-Images/tree/master/grafana
    template.openshift.io/long-description: Vanilla Grafana
    template.openshift.io/provider-display-name: Nicolas Massé
    template.openshift.io/support-url: https://github.com/nmasse-itix/OpenShift-Docker-Images/issues
  name: grafana-nodatasource
objects:

- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: grafana-dashboards
    namespace: ${NAMESPACE}
    labels:
      template: grafana-nodatasource
  data:

- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: grafana-datasources
    namespace: ${NAMESPACE}
    labels:
      template: grafana-nodatasource
  data:

##
## Template Parameters
##
parameters:
- description: The namespace to instantiate Grafana under. Defaults to 'openshift-metrics'.
  name: NAMESPACE
  value: openshift-metrics
